[toolchain]

[features]

[programs.devnet]
token_2022 = "8yBJWQpCAHi1MKUiX9xPf5YqwXV1bat8r4oD85AyFpee"

[registry]
url = "https://api.dev.solana.com"

[provider]
cluster = "Devnet"
wallet = "/home/twzrd/.config/solana/devnet/token_2022-keypair.json"

[scripts]
test = "yarn run ts-mocha --require ts-node/register tests/**/*.test.ts"
