[features]
seeds = true
skip-lint = false

[programs.localnet]
token_2022 = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'Add anchor tests if needed'"

[test]
startup_wait = 10000
