[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = true

[programs.mainnet]
channel_vault = "8szQjRkv1PPaFAo3KUb2eEv5ZZQGr4grACRhktcMEiL4"
wzrd_rails = "BdSv824hvYeGAWQZUcypRzAor8yJit2qeqCHty3CSZy9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
