module.exports = {
  apps: [
    {
      name: 'cls-discovery',
      script: 'tsx',
      args: 'scripts/ops/update-cls-channels.ts',
      cwd: '/home/twzrd/milo-token',
      // Run hourly at minute 0
      cron_restart: '0 * * * *',
      autorestart: false,
      env: {
        NODE_ENV: 'production',
        CLS_RESTART_COMMAND: 'pm2 restart cls-worker',
        // Active hours in UTC (default: 14-5 = 08:00–23:00 CST after DST)
        CLS_DISCOVERY_ACTIVE_START_UTC: '14',
        CLS_DISCOVERY_ACTIVE_END_UTC: '5',
      },
    },
    {
      name: 'cls-worker-s0',
      script: 'dist/index.js',
      cwd: '/home/twzrd/milo-token/apps/worker-v2',
      max_memory_restart: '500M',
      exp_backoff_restart_delay: 5000,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'production',
        WORKER_ID: 'cls-worker-s0',
        SHARD_INDEX: '0',
        TOTAL_SHARDS: '2',
        HEALTH_PORT: '8081',
        CHANNELS_FILE: '/home/twzrd/milo-token/config/cls-channels.txt',
        CHANNELS: '',
        MILO_CHANNELS: '',
        CLS_BLOCKLIST: 'threadguy_live,thread_guytv,threadguys,thraedguy,thread_guy',
        WORKER_JOIN_PER_BATCH: '12',
        WORKER_JOIN_WINDOW_MS: '10000',
        TWZRD_URL: 'http://127.0.0.1:8080',
        LOG_LEVEL: 'debug',
      },
    },
    {
      name: 'cls-worker-s1',
      script: 'dist/index.js',
      cwd: '/home/twzrd/milo-token/apps/worker-v2',
      max_memory_restart: '500M',
      exp_backoff_restart_delay: 5000,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'production',
        WORKER_ID: 'cls-worker-s1',
        SHARD_INDEX: '1',
        TOTAL_SHARDS: '2',
        HEALTH_PORT: '8083',
        CHANNELS_FILE: '/home/twzrd/milo-token/config/cls-channels.txt',
        CHANNELS: '',
        MILO_CHANNELS: '',
        CLS_BLOCKLIST: 'threadguy_live,thread_guytv,threadguys,thraedguy,thread_guy',
        WORKER_JOIN_PER_BATCH: '12',
        WORKER_JOIN_WINDOW_MS: '10000',
        TWZRD_URL: 'http://127.0.0.1:8080',
        LOG_LEVEL: 'debug',
      },
    },
  ],
};
