# NOTE: Disabled vendor source override for dev/tests to allow pulling solana-program-test and friends.
# [source.crates-io]
# replace-with = "vendored-sources"

# [source.vendored-sources]
# directory = "vendor"
